# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f579aabe14a941c1ebdf84f67f1095eb74ddd28178e06d4797fd9d8f6c0a8c727bb732ab5eff1147a2a5f10b960487739e59e15055662eff890d83247a10c910

test:
  secret_key_base: bb9aa4d0e8ef95976c7e2392f122b0587d856aaa412e94c5c5f643f610b09e59211c4e8d6f7c40ba1b00582cac06e57e3cf62d15736e2084442680a49e96c34c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
