# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8230cd7bac0cbef04796600acc2ad8514d3f159138875705d1fb4e3bdd1f3d93dc5e26a808bf0877afb48c83b814101eb176547cfb21a97c4f9f45c7cc14eb0

test:
  secret_key_base: 305c4c249ebc401d52d1d90700e1b8374d52489005afdcfd2fe7859fa00d5899730c2fa4d31922cf8b8c5e8961b46a4a76137ccbfb90767f85532dbcbd90ae5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
