# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa3546cc216ef873282cdf0eef20fe1c10b9a82f888f0daa5045c0ee2d3024f277cd5d028d346bc75c2868859bf78391134bbdf13a31172eb318e7f08a11038a

test:
  secret_key_base: 264994eecb93313a849f3d9a4395485e8b0462b49a90bba88b75a47fe42cced8dd74c542b1638e40c14cb96aa8435b7106507d02f6d17064a505aab9d7fa268b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
