# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e1a8b0ac17c939e8629fb07928b6eaae4bbc79c5df95a427e053ab4439587ca546c9762acd1763036b0647d8b25f54032473b9dde632e974d9244060ff5380

test:
  secret_key_base: b28965ff78421c11fac13605448363475ac939041e51aa6d26acb4490d03f38413c51ebc2a824adbc6e648e797320095101e442387000f992aef6c4a77b408d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
